export default {
    login: "/login",
    register: "/register",
    getAuth: "/getAuth",
    getProducts: "/getProducts",
    getProduct: "/getProduct",
    addToCart: "/addToCart",
    addAddress: "/addAddress",
    getRelevance: "/getRelevance",
    deleteAddress: "/deleteAddress",
    updateUserData: "/updateUserData",
    setOrder: "/setOrder",
    getHotProducts: "getHotProducts",
    getSearchProducts: "getSearchProducts",
    upload: "upload",
}